
project_id = "iilbczoanafeqzjqovjb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[realtime]
enabled = true

[functions.dice-roll]
verify_jwt = true
